In [337]:
import numpy as np 
import sympy as sym
from tqdm import tqdm
import matplotlib.pyplot as mlt

In [126]:
x=sym.Symbol('x')
n=20

In [6]:
def polinomio_laguerre(n,x):
    f=sym.exp(-x)*(x**n)
    l=(sym.exp(x)/sym.factorial(n))*sym.diff(f,x,n)
    return sym.simplify(l)

In [111]:
polinomio_laguerre(2,x)

x**2/2 - 2*x + 1

In [322]:
def GetNewton(f,df,xn,itmax=1000,precision=1e-12):
    
    error = 1.
    it = 0
    
    while error >= precision and it < itmax:
        
        try:
            
            xn1 = xn - f(xn)/df(xn)
            
            error = np.abs(xn1-xn)/np.abs(xn)
            
            #error = np.abs(f(xn)/df(xn))
            
        except ZeroDivisionError:
            print('Zero Division')
            
        xn = xn1
        it += 1
        
    if it == itmax:
        return False
    else:
        return xn

In [330]:
def GetRoots(f,df,x,tolerancia = 5):
    
    Roots = np.array([])
    
    for i in x:
        
        root = GetNewton(f,df,i)

        if  root != False:
            croot = np.round( root, tolerancia )
            
            if croot not in Roots:
                Roots = np.append(Roots, croot)
                
    Roots.sort()
    
    return Roots

In [331]:
def derivada(n):
    polinomio=polinomio_laguerre(n,x)
    return sym.diff(polinomio,x,1)

In [332]:
derivada(2)

x - 2

In [354]:
def GetAllRoots_l(x1,n=20):
    x=sym.Symbol('x',real=True)
    polinomio=polinomio_laguerre(n,x)
    poly=sym.lambdify([x],polinomio, 'numpy')
    Dpoly=sym.lambdify([x],derivada(n), 'numpy')
    
    return GetRoots(poly, Dpoly, x1)

In [355]:
x1 = np.linspace(0.0001,100,1000)

In [356]:
GetAllRoots_l(x1)

array([ 0.07054,  0.37213,  0.91658,  1.70731,  2.7492 ,  4.04893,
        5.61517,  7.45902,  9.59439, 12.0388 , 14.81429, 17.9489 ,
       21.47879, 25.4517 , 29.93255, 35.01343, 40.83306, 47.61999,
       55.8108 , 66.52442])

In [339]:
polinomio=polinomio_laguerre(20,x)
poly=sym.lambdify([x],polinomio, 'numpy')

In [361]:
def GetWeights(n=20):
    polinomio=polinomio_laguerre(21,x)
    poly=poly=sym.lambdify([x],polinomio, 'numpy')
    Roots=GetAllRoots_l(x1)
    return Roots/((21**2)*(poly(Roots)**2))

In [362]:
GetWeights()

array([1.68735983e-01, 2.91152280e-01, 2.66711186e-01, 1.65988625e-01,
       7.48252337e-02, 2.49632327e-02, 6.20277596e-03, 1.14494636e-03,
       1.55743683e-04, 1.54015743e-05, 1.08649671e-06, 5.33006738e-08,
       1.75797544e-09, 3.72551832e-11, 4.76756116e-13, 3.37286128e-15,
       1.15501103e-17, 1.53952769e-20, 5.28642612e-24, 1.65645307e-28])

In [363]:
roots, weights=np.polynomial.laguerre.laggauss(n)
roots, weights #Verificar valores reales

(array([ 0.07053989,  0.37212682,  0.9165821 ,  1.70730653,  2.74919926,
         4.04892531,  5.61517497,  7.45901745,  9.59439287, 12.03880255,
        14.81429344, 17.94889552, 21.47878824, 25.45170279, 29.93255463,
        35.01343424, 40.83305706, 47.61999405, 55.81079575, 66.52441653]),
 array([1.68746802e-01, 2.91254362e-01, 2.66686103e-01, 1.66002453e-01,
        7.48260647e-02, 2.49644173e-02, 6.20255084e-03, 1.14496239e-03,
        1.55741773e-04, 1.54014409e-05, 1.08648637e-06, 5.33012091e-08,
        1.75798118e-09, 3.72550240e-11, 4.76752925e-13, 3.37284424e-15,
        1.15501434e-17, 1.53952214e-20, 5.28644273e-24, 1.65645661e-28]))